//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infoSysBackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class chlPart
    {
        public int idObrac { get; set; }
        public Nullable<int> idPart { get; set; }
        public string surn { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public string dolzn { get; set; }
        public string city { get; set; }
    
        public virtual appeal appeal { get; set; }
    }
}
