//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infoSysBackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class profilesLink
    {
        public int idUsera { get; set; }
        public string link { get; set; }

        public profilesLink()
        {

        }

        public profilesLink(string link)
        {
            this.link = link;
        }
    }
}
