//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infoSysBackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public Nullable<int> idUsera { get; set; }
        public int idObras { get; set; }
    
        public virtual appeal appeal { get; set; }
        public virtual user user { get; set; }
    }
}
